### ISSUE TITLE
运行npm run dev:h5:ssr，页面出错

### ISSUE THREAD

**Issue by 350469960** [amebyte/vue3-vite-ts-uniapp#3]
TypeError: uni.getSystemInfo is not a function
    at Module.createApp (/Users/xunwu/docod/test/vue3-vite-ts-uniapp/src/main.ts:6:20)
    at render (/Users/xunwu/docod/test/vue3-vite-ts-uniapp/src/entry-server.js:14:34)
    at /Users/xunwu/docod/test/vue3-vite-ts-uniapp/node_modules/@dcloudio/vite-plugin-uni/dist/cli/server.js:63:82
    
    
   运行环境
   node: 14.19.3
   yarn: 3.4.1

**Comment by amebyte** [comment]
ssr的，我没测试过
